md "Todos os times"
cd "Todos os times"
md "Serie A"
md "Serie B"
cd "Serie A"
md "Atletico-MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Athletico-PR"
md "Atlético-GO"
md "Ceará"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "São Paulo"
md "Fluminense"
md "Cuiabá"
md "Sport"
md "America-MG"
md "Gremio"
md "Chapecoense"
 