md "Todos os paises"
cd "Todos os paises"
md "Argentina"
md "Bolivia"
md "Brasil"
md "Chile"
md "Colombia"
md "Equador"
md "Guiana"
md "Guiana Francesa"
md "Paraguai"
md "Peru"
md "Suriname"
md "Uruguai"
md "Venezuela"
cd "Brasil"
md "Goias"
md "Mato Grosso"
md "Mato Grosso do Sul"
md "Distrito Federal"
md "Alagoas"
md "Bahia"
md "Ceara"
md "Maranhao"
md "Paraiba"
md "Pernambuco"
md "Piaui"
md "Rio Grande do norte"
md "Sergipe"
