md "Todos os times"
cd "Todos os times"
md "Serie A"
md "Serie B"
cd "Serie A"
md "Atletico-MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Athletico-PR"
md "Atlético-GO"
md "Ceará"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "São Paulo"
md "Fluminense"
md "Cuiabá"
md "Sport"
md "America-MG"
md "Gremio"
md "Chapecoense"
cd..
cd "Serie B"
md "Curitiba"
md "Goias"
md "Avai"
md "CRB"
md "Sampaio Correa"
md "Guarani"
md "Nautico"
md "Botafogo"
md "Operario-PR"
md "CSA"
md "Vasco"
md "Remo"
md "Brusque"
md "Cruzeiro"
md "Vila Nova"
md "Ponte Preta"
md "Londrina"
md "Vitoria"
md "Confianca"
md "Brasil de Pelotas" 